/* ACTION TYPES */

/* AUTH */
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const LOGOUT = 'LOGOUT'

/* Qr */

export const FETCH_ALL_QRS_START = 'FETCH_ALL_QRS_START'
export const FETCH_ALL_QRS_SUCCESS = 'FETCH_ALL_QRS_SUCCESS'
export const FETCH_ALL_QRS_ERROR = 'FETCH_ALL_QRS_ERROR'

export const CREATE_QR_START = 'CREATE_QR_START'
export const CREATE_QR_SUCCESS = 'CREATE_QR_SUCCESS'
export const CREATE_QR_ERROR = 'CREATE_QR_ERROR'

export const DELETE_QR_START = 'DELETE_QR_START'
export const DELETE_QR_SUCCESS = 'DELETE_QR_SUCCESS'
export const DELETE_QR_ERROR = 'DELETE_QR_ERROR'
